### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by wattnpapa** [nafg/gitlab-ci-runner-scala#3]
Hi i get this error any idea how to fix it?

```
java.io.IOException: Cannot run program "cmd /c C:\Users\build\.gitlab-ci-runner-scala\projects\build-2-15-script.bat" (in directory "C:\Users\build\.gitlab-ci-runner-scala\projects"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
```

**Comment by nafg** [comment]
Can you post the full stack trace please?

**Comment by nafg** [comment]
Hmm, I don't think I actually tested it on Windows. Can you try changing

https://github.com/nafg/gitlab-ci-runner-scala/blob/a5bf6a08f35965fcbe09070c5ee8cb8bca712a1d/src/main/scala/gitlab_ci_runner/runner/Build.scala#L78

to say `"cmd.exe"` rather than just `"cmd"` please?

Thanks.

**Comment by wattnpapa** [comment]
Ok i will try it on friday.

The file ist still at the given Path and i can execute ist manually.

The Translation of the last Part of the Error:

```
Das System kann die angegebene Datei nicht finden
The System can not find the given file
```

**Comment by nafg** [comment]
Yeah, I'm suspecting it's "cmd" that can't be found.

**Comment by wattnpapa** [comment]
Ok here is the wohle Error Message i get form the GitLab CI GUI:

```
java.io.IOException: Cannot run program "cmd /c C:\Users\build\.gitlab-ci-runner-scala\projects\build-2-15-script.bat" (in directory "C:\Users\build\.gitlab-ci-runner-scala\projects"): CreateProcess error=2, Das System kann die angegebene Datei nicht finden
    at java.lang.ProcessBuilder.start(Unknown Source)
    at gitlab_ci_runner.runner.Build.exec(Build.scala:98)
    at gitlab_ci_runner.runner.Build.run(Build.scala:62)
    at gitlab_ci_runner.runner.Runner$$anonfun$1.apply$mcV$sp(Runner.scala:27)
    at gitlab_ci_runner.runner.Runner$$anonfun$1.apply(Runner.scala:24)
    at gitlab_ci_runner.runner.Runner$$anonfun$1.apply(Runner.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
    at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
    at scala.concurrent.impl.ExecutionContextImpl$$anon$3.exec(ExecutionContextImpl.scala:107)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.io.IOException: CreateProcess error=2, Das System kann die angegebene Datei nicht finden
    at java.lang.ProcessImpl.create(Native Method)
    at java.lang.ProcessImpl.<init>(Unknown Source)
    at java.lang.ProcessImpl.start(Unknown Source)
    ... 13 more
```

**Comment by nafg** [comment]
Please try changing `cmd` to `cmd.exe`.

Are you running the release jar or building from source yourself?
